version: '3.12'

services:
  web:
    build: .
    command: fastapi run main.py --port 80
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - postgres
      - redis
      - worker
